[package]
name = "leto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# ── Systems and Parallelization ──
mnemosyne = { workspace = true, optional = true }

# ── Numeric Foundations ──
bytemuck = { workspace = true }
eunomia = { workspace = true }
half = { workspace = true }

# ── Error Handling ──
thiserror = { workspace = true }

# ── Optional Compatibility ──
ndarray = { workspace = true, optional = true }

[features]
default = ["std", "parallel", "mnemosyne-memory"]
std = []
alloc = []
parallel = []
# mnemosyne integration
mnemosyne-alloc = ["dep:mnemosyne", "alloc"]
mnemosyne-memory = ["mnemosyne-alloc"]
# ndarray integration
ndarray-compat = ["dep:ndarray", "std"]

[dev-dependencies]
proptest = { workspace = true }
ndarray = { workspace = true }
