[package]
name = "leto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
# ── Systems and Parallelization ──
mnemosyne = { workspace = true, optional = true }

# ── Numeric Foundations ──
bytemuck = { workspace = true }
aequitas = { workspace = true }
eunomia = { workspace = true }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }

# ── Error Handling ──
thiserror = { workspace = true }

# ── Optional Compatibility ──
ndarray = { workspace = true, optional = true }

[features]
default = ["std", "parallel", "mnemosyne-memory"]
std = ["aequitas/std", "serde/std"]
alloc = ["serde/alloc"]
parallel = []
# mnemosyne integration
mnemosyne-alloc = ["dep:mnemosyne", "alloc"]
mnemosyne-memory = ["mnemosyne-alloc"]
ndarray-compat = ["dep:ndarray", "std"]
serde = ["dep:serde"]

[dev-dependencies]
ndarray = { workspace = true }
proptest = { workspace = true }
serde_json = { workspace = true }
